### ISSUE TITLE
Crash with version 1.5.1 - 1.5.0 works fine

### ISSUE THREAD

**Issue by mrniddala** [dangbroitsdon/Wall-Jump-Unofficial#15]
[16:57:54] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:879) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer:289) ~[?:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zgd000$modifiedRunLoop(MinecraftServer:3385) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:644) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
	at net.minecraft.server.network.ServerPlayerEntity.handler$ecb000$wju$tickLogic(ServerPlayerEntity:19759) ~[?:?]
	at net.minecraft.server.network.ServerPlayerEntity.tick(ServerPlayerEntity:482) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:712) ~[?:?]
	at net.minecraft.world.World.tickEntity(World:466) ~[?:?]
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:371) ~[?:?]
	at net.minecraft.world.EntityList.forEach(EntityList:54) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:339) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:875) ~[server-intermediary.jar:?]
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.server.network.ServerPlayerEntity.handler$ecb000$wju$tickLogic(ServerPlayerEntity:19759) ~[?:?]
	at net.minecraft.server.network.ServerPlayerEntity.tick(ServerPlayerEntity:482) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tickEntity(ServerWorld:712) ~[?:?]
	at net.minecraft.world.World.tickEntity(World:466) ~[?:?]
	at net.minecraft.server.world.ServerWorld.method_31420(ServerWorld:371) ~[?:?]
	at net.minecraft.world.EntityList.forEach(EntityList:54) ~[?:?]
	at net.minecraft.server.world.ServerWorld.tick(ServerWorld:339) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:875) ~[server-intermediary.jar:?]
	... 6 more

**Comment by dangbroitsdon** [comment]
this easy fix

**Comment by mrniddala** [comment]
Perfect, otherwise everything works great ❤️
One question: I have op permission and when I change the Double Jump Count it works on the server. Is this intended?
I mean, that the client ignores the server value (still on 1) or is this because of my op permissions?

**Comment by dangbroitsdon** [comment]
thank you for telling me about that, i know what i have to do to fix that, ill implement it into the update as soon as my ide works

**Comment by dangbroitsdon** [comment]
is fixed now

**Comment by mrniddala** [comment]
Thanks for your hard work 🥰

**Comment by dangbroitsdon** [comment]
NO THANK YOU!!!!!!!!!!!
