### ISSUE TITLE
The game crashes on startup

### ISSUE THREAD

**Issue by kr3nr** [dangbroitsdon/Wall-Jump-Unofficial#19]
22:16:14.276
[22:16:14] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
22:16:15.586
[22:16:15] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
22:16:15.612
[22:16:15] [main/INFO] [op.OptiFineTransformer/]: Targets: 382
22:16:16.936
[22:16:16] [main/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
22:16:18.727
[22:16:18] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
22:16:18.835
[22:16:18] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19-forge-41.1.0, --gameDir, /Users/karenrojas/Library/Application Support/minecraft, --assetsDir, /Users/karenrojas/Library/Application Support/minecraft/assets, --uuid, aa713e6817da4704b8b763be5e027d05, --username, kr3nr, --assetIndex, 1.19, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, MDlGNjk4RTI5RDQ1NEJFOTgzNjZCRUY4OEJGRUY0RjE=, --xuid, 2535424548106838, --userType, msa, --versionType, release]
22:16:20.075
[22:16:20] [main/INFO] [ne.mi.co.Co.uteamcore/COREMODLOG]: Injected ASMUContainerMenuHook call into ServerPlayer#initMenu
22:16:20.310
[22:16:20] [main/WARN] [mixin/]: Error loading class: me/cominixo/betterf3/modules/TargetModule (java.lang.ClassNotFoundException: me.cominixo.betterf3.modules.TargetModule)
22:16:20.310
[22:16:20] [main/WARN] [mixin/]: @Mixin target me.cominixo.betterf3.modules.TargetModule was not found securitycraft.mixins.json:f3.BetterF3TargetModuleMixin
22:16:23.158
[22:16:23] [main/WARN] [mixin/]: Error loading class: me/shedaniel/autoconfig/ConfigHolder (java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigHolder)
22:16:23.304
Process crashed with exit code 1

**Comment by dangbroitsdon** [comment]
send me your modlist.

**Comment by kr3nr** [comment]
Same error using only this mod, without any other additional.
walljump-unofficial-forge-1.5.1.1+1.19-1.19.2

21:42:24.215
launcher
main
Preparing to launch minecraft client for 1.19-forge-41.1.0
21:42:24.220
launcher
main
Prepared asset index
21:42:25.351
launcher
main
Have 3446 total files to check or download
21:42:39.610
launcher
main
Minecraft client 1.19-forge-41.1.0 is ready to start.
21:42:39.611
launcher
main
Starting!
21:42:39.611
launcher
main
Nothing to download!
21:42:39.611
launcher
main
Nothing to extract!
21:42:39.611
launcher
main
Version does not support log configuration, will assume one plaintext entry per line
21:42:46.808
game
2022-08-18 21:42:46,780 main WARN Advanced terminal features are not available in this environment
21:42:47.170
game
[21:42:47] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, kr3nr, --version, 1.19-forge-41.1.0, --gameDir, /Users/karenrojas/Library/Application Support/minecraft, --assetsDir, /Users/karenrojas/Library/Application Support/minecraft/assets, --assetIndex, 1.19, --uuid, aa713e6817da4704b8b763be5e027d05, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, MDlGNjk4RTI5RDQ1NEJFOTgzNjZCRUY4OEJGRUY0RjE=, --xuid, 2535424548106838, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 41.1.0, --fml.mcVersion, 1.19, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220607.102129]
21:42:47.178
game
[21:42:47] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.8+10.0.8+main.0ef7e830 starting: java version 17.0.3 by Microsoft; OS Mac OS X arch x86_64 version 10.13.6
21:42:47.489
game
[21:42:47] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/Users/karenrojas/Library/Application%20Support/minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2390!/ Service=ModLauncher Env=CLIENT
21:42:48.508
game
[21:42:48] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /Users/karenrojas/Library/Application Support/minecraft/libraries/net/minecraftforge/fmlcore/1.19-41.1.0/fmlcore-1.19-41.1.0.jar is missing mods.toml file
21:42:48.522
game
[21:42:48] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /Users/karenrojas/Library/Application Support/minecraft/libraries/net/minecraftforge/javafmllanguage/1.19-41.1.0/javafmllanguage-1.19-41.1.0.jar is missing mods.toml file
21:42:48.544
game
[21:42:48] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /Users/karenrojas/Library/Application Support/minecraft/libraries/net/minecraftforge/lowcodelanguage/1.19-41.1.0/lowcodelanguage-1.19-41.1.0.jar is missing mods.toml file
21:42:48.583
game
[21:42:48] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /Users/karenrojas/Library/Application Support/minecraft/libraries/net/minecraftforge/mclanguage/1.19-41.1.0/mclanguage-1.19-41.1.0.jar is missing mods.toml file
21:42:48.777
game
[21:42:48] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
21:42:48.914
game
[21:42:48] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing mandatory dependencies: architectury
21:42:51.170
game
[21:42:51] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
21:42:51.172
game
[21:42:51] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.19-forge-41.1.0, --gameDir, /Users/karenrojas/Library/Application Support/minecraft, --assetsDir, /Users/karenrojas/Library/Application Support/minecraft/assets, --uuid, aa713e6817da4704b8b763be5e027d05, --username, kr3nr, --assetIndex, 1.19, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, MDlGNjk4RTI5RDQ1NEJFOTgzNjZCRUY4OEJGRUY0RjE=, --xuid, 2535424548106838, --userType, msa, --versionType, release]
21:43:02.945
game
at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
21:43:02.945
game
at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
21:43:02.945
game
at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.8.jar:10.0.8+10.0.8+main.0ef7e830] {}
21:43:02.945
game
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.8.jar:?] {}
21:43:02.945
game
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.8.jar:?] {}
21:43:02.945
game
at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.8.jar:?] {}
21:43:02.946
game
at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.4.jar:?] {}
21:43:02.946
game
at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
21:43:02.946
game
at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.4.jar:?] {}
21:43:02.946
game
at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.4.jar:?] {}
21:43:02.946
game
at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.4.jar:?] {}
21:43:02.946
game
at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
21:43:02.946
game
at net.minecraft.client.main.Main$2.run(Main.java:152) ~[client-1.19-20220607.102129-srg.jar%23145!/:?] {re:classloading}
21:43:02.946
game
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: me.shedaniel.autoconfig.ConfigHolder
21:43:02.946
game
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:754) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
21:43:02.946
game
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:739) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
21:43:02.946
game
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:310) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
21:43:02.946
game
at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
21:43:02.946
game
at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
21:43:02.946
game
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
21:43:02.946
game
at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
21:43:02.946
game
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
21:43:02.946
game
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
21:43:02.946
game
... 14 more
21:43:03.033
monitor
Process Monitor
Process crashed with exit code 1

**Comment by dangbroitsdon** [comment]
install this mod and it should fix it:

https://www.curseforge.com/minecraft/mc-mods/cloth-config/files
