### ISSUE TITLE
Update to 1.19.4?

### ISSUE THREAD

**Issue by blackshot** [dangbroitsdon/Wall-Jump-Unofficial#39]
Plugin loads without error, but when i try to join a server i get this

```
[20:17:45] [Render thread/INFO]: Stopping worker threads
[20:17:45] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Ticking entity
	at net.minecraft.class_1937.method_18472(class_1937.java:495) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_32124(class_638.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:248) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1902) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1180) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.17.jar:?]
Caused by: java.lang.IllegalAccessError: class fabric.genandnic.walljump.logic.MiscLogic tried to access private field net.minecraft.class_1297.field_6013 (fabric.genandnic.walljump.logic.MiscLogic and net.minecraft.class_1297 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4c70fda8)
	at fabric.genandnic.walljump.logic.MiscLogic.doStepAssist(MiscLogic.java:19) ~[walljump-unofficial-1.6.4-all-networking-removed+1.19.3.jar:?]
	at net.minecraft.class_746.handler$blb000$walljump-fabric$wju$tickPlayerLogic(class_746.java:3321) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_6007(class_746.java:849) ~[client-intermediary.jar:?]
	at net.minecraft.class_1309.method_5773(class_1309.java:2400) ~[client-intermediary.jar:?]
	at net.minecraft.class_1657.method_5773(class_1657.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.class_742.method_5773(class_742.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.class_746.method_5773(class_746.java:217) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18646(class_638.java:269) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:488) ~[client-intermediary.jar:?]
	... 10 more
```

**Comment by grimdaybreaker** [comment]
could you at least post a version where its only single player? I want to use other mods with this one

**Comment by sternschnaube** [comment]
I saw this here now: https://modrinth.com/mod/wall-jumped
For anyone who can't wait until we got the 1.19.4 version, it's a good choice for now.

**Comment by kkrnjc** [comment]
1.19.4 pls yes

**Comment by dangbroitsdon** [comment]
#44
